// ---------------- Scan Products ---------------------//
export const START_GET_SCAN_PRODUCTS = 'START_GET_SCAN_PRODUCTS';
export const SUCCESS_GET_SCAN_PRODUCTS = 'SUCCESS_GET_SCAN_PRODUCTS';
export const FAILED_GET_SCAN_PRODUCTS = 'FAILED_GET_SCAN_PRODUCTS';
// ---------------- Scan Product Details ---------------------//
export const START_GET_SCAN_PRODUCT_DETAILS = 'START_GET_SCAN_PRODUCT_DETAILS';
export const SUCCESS_GET_PRODUCT_DETAILS = 'SUCCESS_GET_PRODUCT_DETAILS';
export const FAILED_GET_PRODUCT_DETAILS = 'FAILED_GET_PRODUCT_DETAILS';
